apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: demo-app
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://demo-app-service.demo-app.svc.cluster.local:80;
      }
    }
